name = "curljson"
version = "0.0.2"
license = "Apache-2.0"
defaultTargets = ["CurlJson"]

[[require]]
name = "Curl"
git = "https://github.com/bergmannjg/leanCurl"
rev = "main"

[[lean_lib]]
name = "CurlJson"
